serverListener:
  tcp:
    host: "127.0.0.1"
    port: 8081

postgres:
  host:     "localhost"
  port:     5432
  username: "postgres"
  dbname:   "postgres"
  sslmode:  "disable"
  password: "postgres"